import { chromium } from 'playwright'
import { spawn } from 'node:child_process'
const server = spawn('npx', ['vite', 'preview', '--port', '4176', '--strictPort', '--host', '127.0.0.1'], { stdio: 'ignore' })
await new Promise((r) => setTimeout(r, 2500))
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 393, height: 852 } })
page.on('console', (m) => console.log('console:', m.type(), m.text()))
page.on('pageerror', (e) => console.log('pageerror:', e.message))
page.on('dialog', d => { console.log('dialog', d.message()); d.accept() })
await page.goto('http://127.0.0.1:4176/')
await page.waitForTimeout(2000)
console.log((await page.content()).slice(0, 300))
await page.goto('http://127.0.0.1:4176/#/settings/sync/oss')
await page.waitForTimeout(1500)
console.log('URL', page.url(), (await page.locator('body').innerText()).slice(0, 200))
await page.goto('http://127.0.0.1:4176/#/entry/2026-10-04')
await page.waitForTimeout(1500)
console.log('URL', page.url(), (await page.locator('body').innerText()).slice(0, 200))
await browser.close(); server.kill()
