import { chromium } from 'playwright'
import { spawn } from 'node:child_process'
const server = spawn('npx', ['vite', 'preview', '--port', '4176', '--strictPort', '--host', '127.0.0.1'], { stdio: 'ignore' })
await new Promise((r) => setTimeout(r, 2500))
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 393, height: 852 } })
page.on('console', (m) => m.type() === 'error' && console.log('console:', m.text()))
page.on('pageerror', (e) => console.log('pageerror:', e.message))
page.on('dialog', d => { console.log('dialog', d.message().slice(0,60)); d.accept() })
const B='http://127.0.0.1:4176/'
await page.goto(B); await page.waitForTimeout(1500)
await page.goto(B + '#/ai'); await page.waitForTimeout(800)
await page.getByRole('link', { name: '添加 AI 服务' }).click()
await page.waitForTimeout(500)
await page.getByRole('combobox').first().selectOption('DeepSeek')
await page.getByLabel('模型名').fill('m'); await page.getByLabel('API Key').fill('k')
await page.getByRole('button', { name: '保存' }).click()
await page.waitForTimeout(800)
console.log('URL', page.url())
await page.goto(B + '#/ai'); await page.waitForTimeout(800)
console.log((await page.locator('body').innerText()).slice(0, 300))
await page.screenshot({ path: 'e2e/scratch/ai.png' })
await page.goto(B + '#/'); await page.waitForTimeout(800)
console.log('HOME', (await page.locator('body').innerText()).slice(0, 200))
await browser.close(); server.kill()
